// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OrderTask.Model;
using System;

namespace OrderTask.Model.Migrations
{
    [DbContext(typeof(OrderTaskContext))]
    [Migration("20180207082144_vicky1")]
    partial class vicky1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("OrderTask.Model.DbModel.BisnessModel.DataManage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaidiAddress")
                        .HasMaxLength(300);

                    b.Property<string>("BiaozhunAddress")
                        .HasMaxLength(300);

                    b.Property<string>("ChangjingAddress")
                        .HasMaxLength(300);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<string>("GuanggaoAddress")
                        .HasMaxLength(300);

                    b.Property<string>("MoteAddress")
                        .HasMaxLength(300);

                    b.Property<string>("ProductNum")
                        .HasMaxLength(200);

                    b.Property<string>("Remark")
                        .HasMaxLength(300);

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<string>("RukouAddress")
                        .HasMaxLength(300);

                    b.Property<string>("TaojiaoAddress")
                        .HasMaxLength(300);

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.Property<string>("XiangxiAddress")
                        .HasMaxLength(300);

                    b.Property<string>("ZhuantiAddress")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("t_DataManage");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.BisnessModel.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ComplateTime");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<int?>("Degree");

                    b.Property<bool>("ExistRefuse");

                    b.Property<DateTime?>("ExpectTime");

                    b.Property<string>("FinishDescribe");

                    b.Property<string>("OrderDescribe");

                    b.Property<string>("OrderName")
                        .HasMaxLength(300);

                    b.Property<int?>("OrderState");

                    b.Property<string>("OrderTypeIds");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.Property<int?>("UserInfoId");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId");

                    b.ToTable("t_Order");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.BisnessModel.OrderLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<string>("Describe");

                    b.Property<int?>("OperationType");

                    b.Property<int?>("Operator");

                    b.Property<int?>("OrderId");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.HasIndex("Operator");

                    b.HasIndex("OrderId");

                    b.ToTable("t_OrderLog");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.BisnessModel.OrderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<string>("TypeName")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("t_OrderType");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.BisnessModel.ReceivePerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CompleteTime");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<int?>("OrderId");

                    b.Property<int?>("ReceiveState");

                    b.Property<DateTime?>("ReceiveTime");

                    b.Property<string>("RefuseResion")
                        .HasMaxLength(500);

                    b.Property<string>("Remark");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.Property<int?>("UserInfoId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("t_ReceivePerson");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.Button", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BtnClass")
                        .HasMaxLength(50);

                    b.Property<string>("BtnIcon")
                        .HasMaxLength(50);

                    b.Property<string>("BtnName")
                        .HasMaxLength(20);

                    b.Property<string>("BtnScript")
                        .HasMaxLength(50);

                    b.Property<string>("BtnTip")
                        .HasMaxLength(50);

                    b.Property<string>("BtnUrl")
                        .HasMaxLength(300);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<string>("DisplayCondition")
                        .HasMaxLength(500);

                    b.Property<int>("EditType");

                    b.Property<bool>("IsActive");

                    b.Property<int>("OrderBy");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<string>("SpName")
                        .HasMaxLength(50);

                    b.Property<int>("SysTableId");

                    b.Property<int?>("TableId");

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("t_sys_Button");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.Column", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ColumnName")
                        .HasMaxLength(30);

                    b.Property<int>("ColumnType");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<string>("DataOptions")
                        .HasMaxLength(300);

                    b.Property<int>("DisplayType");

                    b.Property<int>("FkTableId");

                    b.Property<bool>("IsIndexed");

                    b.Property<bool>("IsShow");

                    b.Property<int>("OrderBy");

                    b.Property<string>("ReMark");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<string>("ShowName")
                        .HasMaxLength(20);

                    b.Property<int?>("TableId");

                    b.Property<string>("Tip")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("t_sys_Column");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.DepartMent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<string>("DptName")
                        .HasMaxLength(20);

                    b.Property<bool>("IsActive");

                    b.Property<int>("OrderBy");

                    b.Property<int>("ParentId");

                    b.Property<string>("ReMark");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("t_sys_DepartMent");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<bool>("IsActive");

                    b.Property<string>("MenuName")
                        .HasMaxLength(20);

                    b.Property<string>("MenuUrl")
                        .HasMaxLength(500);

                    b.Property<int>("OrderBy");

                    b.Property<int?>("ParentMenuId");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<int?>("SubSystemId");

                    b.Property<int?>("SysTableId");

                    b.Property<int?>("TableId");

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.HasIndex("SubSystemId");

                    b.HasIndex("TableId");

                    b.ToTable("t_sys_MenuInfo");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.RoleInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<string>("Describe")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<bool>("IsActive");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("t_sys_RoleInfo");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.RolePower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ButtonId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<int>("MentId");

                    b.Property<int>("RoleId");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<int>("Type");

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("t_sys_RolePower");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.SubSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Link");

                    b.Property<int>("OrderBy");

                    b.Property<string>("ReMark");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<string>("SystemIcon");

                    b.Property<string>("SystemName");

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("t_sys_SubSystem");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsMultiple");

                    b.Property<bool>("IsPaging");

                    b.Property<int>("OrderBy");

                    b.Property<string>("ReMark");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<string>("ShowName");

                    b.Property<string>("TableName");

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("t_sys_Table");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("CreateUserId");

                    b.Property<int?>("DepartMentId");

                    b.Property<string>("Describe")
                        .HasMaxLength(500);

                    b.Property<int?>("Gender");

                    b.Property<string>("Group")
                        .HasMaxLength(100);

                    b.Property<string>("GroupNum")
                        .HasMaxLength(100);

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("JobScheduling");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(11);

                    b.Property<string>("Picture")
                        .HasMaxLength(300);

                    b.Property<string>("Post")
                        .HasMaxLength(300);

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<string>("Skill")
                        .HasMaxLength(100);

                    b.Property<string>("TrueName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(20);

                    b.Property<int?>("UpdateUserId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("DepartMentId");

                    b.HasIndex("TrueName")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("t_sys_UserInfo");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.UserRole", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("t_sys_UserRole");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.BisnessModel.Order", b =>
                {
                    b.HasOne("OrderTask.Model.DbModel.UserInfo", "OrderPerson")
                        .WithMany()
                        .HasForeignKey("UserInfoId");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.BisnessModel.OrderLog", b =>
                {
                    b.HasOne("OrderTask.Model.DbModel.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("Operator");

                    b.HasOne("OrderTask.Model.DbModel.BisnessModel.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.BisnessModel.ReceivePerson", b =>
                {
                    b.HasOne("OrderTask.Model.DbModel.BisnessModel.Order", "Order")
                        .WithMany("ReceivePerson")
                        .HasForeignKey("OrderId");

                    b.HasOne("OrderTask.Model.DbModel.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserInfoId");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.Button", b =>
                {
                    b.HasOne("OrderTask.Model.DbModel.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.Column", b =>
                {
                    b.HasOne("OrderTask.Model.DbModel.Table", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableId");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.Menu", b =>
                {
                    b.HasOne("OrderTask.Model.DbModel.SubSystem", "SubSystem")
                        .WithMany("MenuInfo")
                        .HasForeignKey("SubSystemId");

                    b.HasOne("OrderTask.Model.DbModel.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.UserInfo", b =>
                {
                    b.HasOne("OrderTask.Model.DbModel.DepartMent", "DepartMent")
                        .WithMany("UserInfos")
                        .HasForeignKey("DepartMentId");
                });

            modelBuilder.Entity("OrderTask.Model.DbModel.UserRole", b =>
                {
                    b.HasOne("OrderTask.Model.DbModel.RoleInfo", "RoleInfo")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OrderTask.Model.DbModel.UserInfo", "UserInfo")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
